import { StrictMode } from "react";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { CompanionPage } from "../../src/frontend/src/features/companion/CompanionPage";
const todo={id:"td1",text:"写提纲",project_id:"p",project_name:"选题",done:false,done_at:null,revision:null};
const api=()=>({getWeekStats:vi.fn().mockResolvedValue({remember:12,confirm:8,forget:1,week_start:"2026-09-28"}),listTodos:vi.fn().mockResolvedValue({items:[todo]}),doneTodo:vi.fn().mockResolvedValue({...todo,done:true,done_at:new Date().toISOString(),revision:1}),undoTodo:vi.fn().mockResolvedValue({...todo,revision:2}),sendChat:vi.fn().mockResolvedValue({session:{session_id:"s"},user_message:{message_id:"u",role:"user",content:"你好"},assistant_message:{message_id:"a",role:"assistant",content:"一起想想"}}),getFocus:vi.fn().mockResolvedValue({session:null}),startFocus:vi.fn().mockResolvedValue({session:{session_id:"f",revision:1,status:"running",remaining_seconds:1500}}),actOnFocus:vi.fn().mockResolvedValue({session:{session_id:"f",revision:2,status:"paused",remaining_seconds:1500}})});
afterEach(()=>{vi.useRealTimers();vi.unstubAllGlobals();});
describe("CompanionPage four modes",()=>{
 it("sends real chat requests and shows week counts",async()=>{const a=api();render(<CompanionPage projectId="p" api={a}/>);fireEvent.change(screen.getByLabelText("和小熊说"),{target:{value:"你好"}});fireEvent.click(screen.getByRole("button",{name:"发送"}));expect(await screen.findByText("一起想想")).toBeInTheDocument();expect(a.sendChat).toHaveBeenCalledWith(expect.objectContaining({projectId:"p",text:"你好"}));fireEvent.click(screen.getByRole("button",{name:"回顾"}));expect(await screen.findByText("12")).toBeInTheDocument();expect(screen.getByText("8")).toBeInTheDocument();expect(screen.getByText("1")).toBeInTheDocument();expect(a.getWeekStats).toHaveBeenCalledWith(expect.objectContaining({projectId:"p"}));});
 it("keeps chat while switching modes",async()=>{const a=api();render(<CompanionPage api={a}/>);fireEvent.change(screen.getByLabelText("和小熊说"),{target:{value:"你好"}});fireEvent.click(screen.getByRole("button",{name:"发送"}));await screen.findByText("一起想想");fireEvent.click(screen.getByRole("button",{name:"回顾"}));await screen.findByText("12");fireEvent.click(screen.getByRole("button",{name:"聊聊"}));expect(screen.getByText("一起想想")).toBeVisible();});
 it("starts and pauses the existing focus service",async()=>{const a=api();render(<CompanionPage api={a}/>);fireEvent.click(screen.getByRole("button",{name:"专注"}));fireEvent.click(await screen.findByRole("button",{name:"开始"}));fireEvent.click(await screen.findByRole("button",{name:"暂停"}));await waitFor(()=>expect(a.actOnFocus).toHaveBeenCalledWith(expect.objectContaining({action:"pause",expectedRevision:1})));});
 it("optimistically completes then restores revision bound todo",async()=>{const a=api();let resolve;a.doneTodo.mockImplementation(()=>new Promise(r=>resolve=r));render(<CompanionPage projectId="p" api={a}/>);fireEvent.click(screen.getByRole("button",{name:"安排"}));const box=await screen.findByRole("checkbox",{name:"写提纲"});fireEvent.click(box);expect(box).toBeChecked();expect(box).toBeDisabled();expect(a.doneTodo).toHaveBeenCalledWith(expect.objectContaining({id:"td1",expectedRevision:null}));await act(async()=>resolve({...todo,done:true,done_at:new Date().toISOString(),revision:1}));fireEvent.click(box);await waitFor(()=>expect(a.undoTodo).toHaveBeenCalledWith(expect.objectContaining({expectedRevision:1})));expect(box).not.toBeChecked();});
 it("rolls back failure and retries with a dot",async()=>{const a=api();a.doneTodo.mockRejectedValueOnce(new Error("private detail"));render(<CompanionPage api={a}/>);fireEvent.click(screen.getByRole("button",{name:"安排"}));const box=await screen.findByRole("checkbox",{name:"写提纲"});fireEvent.click(box);const retry=await screen.findByRole("button",{name:"重试写提纲"});expect(box).not.toBeChecked();expect(screen.queryByText("private detail")).not.toBeInTheDocument();fireEvent.click(retry);await waitFor(()=>expect(box).toBeChecked());expect(a.doneTodo).toHaveBeenCalledTimes(2);});
 it("refreshes todo revision before retry and removes vanished rows",async()=>{const a=api();a.doneTodo.mockRejectedValueOnce({status:409});render(<CompanionPage api={a}/>);fireEvent.click(screen.getByRole("button",{name:"安排"}));fireEvent.click(await screen.findByRole("checkbox",{name:"写提纲"}));a.listTodos.mockResolvedValue({items:[{...todo,revision:5}]});fireEvent.click(await screen.findByRole("button",{name:"重试写提纲"}));await waitFor(()=>expect(a.doneTodo).toHaveBeenLastCalledWith(expect.objectContaining({expectedRevision:5})));a.undoTodo.mockRejectedValueOnce({status:404});fireEvent.click(screen.getByRole("checkbox",{name:"写提纲"}));a.listTodos.mockResolvedValue({items:[]});fireEvent.click(await screen.findByRole("button",{name:"重试写提纲"}));await waitFor(()=>expect(screen.queryByText("写提纲")).not.toBeInTheDocument());});
 it("ignores superseded StrictMode focus reads",async()=>{const a=api();let resolve;a.getFocus.mockImplementationOnce(()=>new Promise(r=>resolve=r)).mockResolvedValue({session:{session_id:"new",revision:4,status:"paused",remaining_seconds:1200}});render(<StrictMode><CompanionPage api={a} initialMode="focus"/></StrictMode>);await screen.findByText("20:00");await act(async()=>resolve({session:{session_id:"old",revision:1,status:"running",remaining_seconds:800}}));expect(screen.getByText("20:00")).toBeInTheDocument();});
 it("refreshes focus after conflict without reversing the requested action",async()=>{const a=api();a.getFocus.mockResolvedValue({session:{session_id:"f",revision:1,status:"running",remaining_seconds:1500}});a.actOnFocus.mockRejectedValueOnce({status:409});render(<CompanionPage api={a} initialMode="focus"/>);fireEvent.click(await screen.findByRole("button",{name:"暂停"}));a.getFocus.mockResolvedValue({session:{session_id:"f",revision:6,status:"running",remaining_seconds:1400}});fireEvent.click(await screen.findByRole("button",{name:"重试"}));await waitFor(()=>expect(a.actOnFocus).toHaveBeenLastCalledWith(expect.objectContaining({expectedRevision:6,action:"pause"})));});
 it("retries focus polling as a read without changing session state",async()=>{vi.useFakeTimers();vi.stubGlobal("electronAPI",{backendBaseUrl:"http://127.0.0.1:1234"});const a=api();const running={session_id:"f",revision:1,status:"running",remaining_seconds:1500};a.getFocus.mockResolvedValueOnce({session:running}).mockRejectedValueOnce(new Error("network")).mockResolvedValue({session:running});render(<CompanionPage api={a} initialMode="focus"/>);await act(async()=>{});await act(async()=>{await vi.advanceTimersByTimeAsync(4000);});fireEvent.click(screen.getByRole("button",{name:"重试"}));await act(async()=>{});expect(a.getFocus).toHaveBeenCalledTimes(3);expect(a.actOnFocus).not.toHaveBeenCalled();expect(a.startFocus).not.toHaveBeenCalled();});
 it("isolates a late completion write after changing project",async()=>{const a=api();let resolve;a.doneTodo.mockImplementationOnce(()=>new Promise(r=>resolve=r));const {rerender}=render(<CompanionPage projectId="p" api={a} initialMode="plan"/>);fireEvent.click(await screen.findByRole("checkbox",{name:"写提纲"}));a.listTodos.mockResolvedValue({items:[{...todo,id:"other",text:"新待办"}]});rerender(<CompanionPage projectId="q" api={a} initialMode="plan"/>);expect(await screen.findByRole("checkbox",{name:"新待办"})).not.toBeChecked();await act(async()=>resolve({...todo,done:true,revision:1,done_at:new Date().toISOString()}));expect(screen.getByRole("checkbox",{name:"新待办"})).not.toBeChecked();expect(screen.queryByText("写提纲")).not.toBeInTheDocument();});
 it("filters completed rows by Shanghai calendar date",async()=>{vi.setSystemTime(new Date("2026-10-01T17:00:00Z"));const a=api();a.listTodos.mockResolvedValue({items:[todo,{...todo,id:"today",text:"今天完成",done:true,done_at:"2026-10-01T16:30:00Z"},{...todo,id:"yesterday",text:"昨日完成",done:true,done_at:"2026-10-01T15:30:00Z"}]});render(<CompanionPage api={a}/>);fireEvent.click(screen.getByRole("button",{name:"安排"}));expect(await screen.findByText("今天完成")).toBeInTheDocument();expect(screen.queryByText("昨日完成")).not.toBeInTheDocument();expect(a.listTodos).toHaveBeenCalledWith(expect.objectContaining({includeDone:true}));});
 it("isolates late reads after changing project",async()=>{const a=api();let resolve;a.listTodos.mockImplementationOnce(()=>new Promise(r=>resolve=r)).mockResolvedValue({items:[{...todo,id:"other",text:"新项目"}]});const {rerender}=render(<CompanionPage projectId="p" api={a}/>);fireEvent.click(screen.getByRole("button",{name:"安排"}));rerender(<CompanionPage projectId="q" api={a}/>);expect(await screen.findByText("新项目")).toBeInTheDocument();await act(async()=>resolve({items:[todo]}));expect(screen.queryByText("写提纲")).not.toBeInTheDocument();});
});

it("preserves the existing desktop pet entry",()=>{const enterCompanionMode=vi.fn();vi.stubGlobal("electronAPI",{enterCompanionMode});render(<CompanionPage api={api()}/>);fireEvent.click(screen.getByRole("button",{name:"显示桌宠"}));expect(enterCompanionMode).toHaveBeenCalledOnce();});

it("keeps one chat instance without duplicate-key errors across mode and project changes", async () => {
 const errors=vi.spyOn(console,'error').mockImplementation(()=>{});
 try {
  const a=api();const {rerender}=render(<StrictMode><CompanionPage projectId="p" api={a}/></StrictMode>);
  fireEvent.change(screen.getByLabelText('和小熊说'),{target:{value:'保留的草稿'}});
  for(const mode of ['回顾','安排','专注','聊聊']) {fireEvent.click(screen.getByRole('button',{name:mode,exact:true}));await act(async()=>{});}
  expect(screen.getAllByLabelText('和小熊说')).toHaveLength(1);
  expect(screen.getByLabelText('和小熊说')).toHaveValue('保留的草稿');
  rerender(<StrictMode><CompanionPage projectId="q" api={a}/></StrictMode>);await act(async()=>{});
  expect(screen.getAllByLabelText('和小熊说')).toHaveLength(1);
  expect(screen.getByLabelText('和小熊说')).toHaveValue('');
  expect(errors.mock.calls.filter(args=>args.join(' ').includes('same key'))).toHaveLength(0);
 } finally { errors.mockRestore(); }
});
