name: chriptmas-replay
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ffmpeg
  - pip
  - pip:
    - -r requirements.txt
    - nvidia-cublas-cu12
    - nvidia-cuda-runtime-cu12
    - nvidia-cuda-nvrtc-cu12
    - nvidia-cudnn-cu12
