const test=require("node:test");const assert=require("node:assert/strict");
const {CompanionFocusRuntimeController}=require("../src/companion/focus-runtime-controller.cjs");
function harness(overrides={}){let tick;const calls=[];const controller=new CompanionFocusRuntimeController({readSession:async()=>({session_id:"focus_1",status:"running"}),observe:async(flags)=>{calls.push(flags);return {session_id:"focus_1",status:"running",should_warn:false};},onWarning:()=>{},onComplete:()=>{},setIntervalFn:(fn)=>{tick=fn;return 1;},clearIntervalFn:()=>{},...overrides});return {controller,calls,run:()=>tick?.()};}
test("polls every four seconds and sends only coarse lock sleep and quiet flags",async()=>{const h=harness();h.controller.start();await new Promise(setImmediate);assert.equal(h.controller.intervalMs,4000);assert.deepEqual(h.calls[0],{locked:false,sleeping:false,game_quiet:false});h.controller.setLocked(true);await new Promise(setImmediate);assert.equal(h.calls.at(-1).locked,true);h.controller.stop();});
test("deduplicates completion and warning delivery",async()=>{let warnings=0,completions=0;const h=harness({observe:async()=>({session_id:"focus_1",status:"completed",should_warn:true}),onWarning:()=>warnings++,onComplete:()=>completions++});await h.controller.poll();await h.controller.poll();assert.equal(warnings,2);assert.equal(completions,1);});
test("does not overlap slow observations",async()=>{let release;const pending=new Promise(r=>release=r);let count=0;const h=harness({observe:async()=>{count++;await pending;return {session_id:"focus_1",status:"running",should_warn:false};}});const first=h.controller.poll();await h.controller.poll();assert.equal(count,1);release();await first;});
test("contains transport failures without an unhandled rejection",async()=>{let error;const h=harness({readSession:async()=>{throw new Error("offline");},onError:(value)=>{error=value;}});await h.controller.poll();assert.equal(error.message,"offline");});
test("a suspend observation survives an immediate resume signal",async()=>{const h=harness();h.controller.setSuspended(true);h.controller.setSuspended(false);await new Promise(setImmediate);assert.equal(h.calls.some((flags)=>flags.sleeping===true),true);assert.equal(h.controller.suspendPending,false);});
test("exposes only the current focus-active fact for other quiet-mode controllers",async()=>{let status="running";const h=harness({readSession:async()=>({session_id:"focus_1",status}),observe:async()=>({session_id:"focus_1",status,should_warn:false})});assert.equal(h.controller.isActive(),false);await h.controller.poll();assert.equal(h.controller.isActive(),true);status="completed";await h.controller.poll();assert.equal(h.controller.isActive(),false);});
