import { fireEvent, render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import { Composer } from '@src/shared/ui/Composer';
import { expectNoSevereA11yViolations } from '../../a11y/axeTestUtils';
describe('Composer',()=>{
 it('renders two-line input and selected intent',()=>{render(<Composer intent="remember" projectTag="创作助手"/>);expect(screen.getByRole('textbox',{name:'输入'})).toHaveAttribute('rows','2');expect(screen.getByRole('button',{name:'记住'})).toHaveAttribute('aria-pressed','true');expect(screen.getByText('#创作助手')).toBeInTheDocument();});
 it.each([['https://example.com','remember'],['灵感 新开头','inspiration'],['帮我写选题','do'],['怎么写？','ask']])('preselects %s',(text,intent)=>{const select=vi.fn();render(<Composer intent="do" onIntent={select}/>);fireEvent.change(screen.getByRole('textbox',{name:'输入'}),{target:{value:text}});expect(select).toHaveBeenCalledWith(intent);});
 it('keeps plain text intent and locks after manual selection',()=>{const select=vi.fn();render(<Composer intent="ask" onIntent={select}/>);fireEvent.change(screen.getByRole('textbox',{name:'输入'}),{target:{value:'一些笔记'}});expect(select).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'干活'}));select.mockClear();fireEvent.change(screen.getByRole('textbox',{name:'输入'}),{target:{value:'怎么写？'}});expect(select).not.toHaveBeenCalled();});
 it('shows scope and sends original input',()=>{const select=vi.fn(),send=vi.fn();render(<Composer intent="ask" onIntent={select} onSend={send}/>);fireEvent.change(screen.getByRole('textbox',{name:'输入'}),{target:{value:'#创作助手/选题 一些笔记'}});expect(screen.getByText('#创作助手/选题')).toBeInTheDocument();expect(select).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'发送'}));expect(send).toHaveBeenCalledWith({text:'#创作助手/选题 一些笔记',files:[],intent:'ask'});});
 it('Enter sends while Shift and IME do not',()=>{const send=vi.fn();render(<Composer onSend={send}/>);const input=screen.getByRole('textbox',{name:'输入'});fireEvent.change(input,{target:{value:'笔记'}});fireEvent.keyDown(input,{key:'Enter',shiftKey:true});fireEvent.compositionStart(input);fireEvent.keyDown(input,{key:'Enter'});expect(send).not.toHaveBeenCalled();fireEvent.compositionEnd(input);fireEvent.keyDown(input,{key:'Enter'});expect(send).toHaveBeenCalledTimes(1);});
 it('adds and removes files and delegates microphone',()=>{const select=vi.fn(),record=vi.fn();const {container}=render(<Composer intent="ask" onIntent={select} onRecord={record}/>);const file=new File(['x'],'笔记.txt');fireEvent.change(container.querySelector('input[type=file]'),{target:{files:[file]}});expect(select).toHaveBeenCalledWith('remember');fireEvent.click(screen.getByRole('button',{name:'移除 笔记.txt'}));expect(screen.queryByText('笔记.txt')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'录音'}));expect(record).toHaveBeenCalledTimes(1);});
 it('has no serious accessibility violations',async()=>{const {container}=render(<Composer/>);await expectNoSevereA11yViolations(container);});
 it('follows external intent after automatic selection',()=>{const {rerender}=render(<Composer intent="do" onIntent={()=>{}}/>);fireEvent.change(screen.getByRole('textbox',{name:'输入'}),{target:{value:'https://example.com'}});rerender(<Composer intent="ask" onIntent={()=>{}}/>);expect(screen.getByRole('button',{name:'问'})).toHaveAttribute('aria-pressed','true');});
 it('preserves draft when no send callback exists',()=>{render(<Composer/>);fireEvent.change(screen.getByRole('textbox',{name:'输入'}),{target:{value:'草稿'}});fireEvent.keyDown(screen.getByRole('textbox',{name:'输入'}),{key:'Enter'});expect(screen.getByRole('textbox',{name:'输入'})).toHaveValue('草稿');});
 it('parses a scope at a CRLF line boundary',()=>{render(<Composer projectTag="我"/>);fireEvent.change(screen.getByRole('textbox',{name:'输入'}),{target:{value:'笔记 #创作助手/选题\r\n第二行'}});expect(screen.getByText('#创作助手/选题')).toBeInTheDocument();});
});
