"""Core-owned acceptance of completed LineMap replay nodes.

This module is deliberately an evidence validator and immutable receipt writer.
It neither starts a Turn nor calls a model, and it has no recovery loop. One
plan is fenced to one already-confirmed, stale source graph revision; it also
reserves a distinct result graph revision for a later bridge. Accepting a node
does *not* mutate a Snapshot or inject that output into the next node's model
input. Only after all receipts can a future bridge append the result Snapshot
with the source revision as its predecessor CAS. Replay ordering and all
CAS/idempotency checks stay here in the Context Graph platform contract.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Mapping, Protocol

from .compiler import FrozenContextRevisions
from .models import ContextGraphSnapshot
from .staleness import stale_replay_order
from .validation import validate_snapshot


class ReplayCompletionError(ValueError):
    """A replay completion is incomplete, forged, stale, or out of order."""


class ReplayCompletionConflict(ReplayCompletionError):
    """An immutable request or receipt identity was reused with different data."""


def _text(value: object, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ReplayCompletionError(f"invalid_{field}")
    return value


def _unique_texts(value: object, field: str) -> tuple[str, ...]:
    if type(value) is not tuple or any(not isinstance(item, str) or not item.strip() for item in value):
        raise ReplayCompletionError(f"invalid_{field}")
    if len(value) != len(set(value)):
        raise ReplayCompletionError(f"duplicate_{field}")
    return value


@dataclass(frozen=True, slots=True)
class ReplayPlan:
    """One immutable, already-confirmed stale replay plan.

    ``input_fingerprints`` are generated by the compiler/Turn bridge and are
    opaque here.  The platform accepts them only when the exact plan and its
    downstream completion request agree; no caller may substitute a new input
    fingerprint after a plan is frozen.  They describe the fixed source graph,
    not an output produced by an earlier receipt in this same plan.
    """

    replay_plan_id: str
    project_id: str
    graph_id: str
    source_graph_revision: str
    result_graph_revision: str
    node_ids: tuple[str, ...]
    input_fingerprints: tuple[tuple[str, str], ...]
    binding_ref: str
    revisions: FrozenContextRevisions

    def __post_init__(self) -> None:
        for field in (
            "replay_plan_id", "project_id", "graph_id", "source_graph_revision",
            "result_graph_revision", "binding_ref",
        ):
            _text(getattr(self, field), field)
        if self.source_graph_revision == self.result_graph_revision:
            raise ReplayCompletionError("replay_result_revision_unchanged")
        node_ids = _unique_texts(self.node_ids, "replay_plan_node_ids")
        if not node_ids:
            raise ReplayCompletionError("empty_replay_plan")
        if not isinstance(self.revisions, FrozenContextRevisions):
            raise ReplayCompletionError("invalid_replay_revisions")
        if type(self.input_fingerprints) is not tuple:
            raise ReplayCompletionError("invalid_replay_input_fingerprints")
        fingerprints: dict[str, str] = {}
        for item in self.input_fingerprints:
            if type(item) is not tuple or len(item) != 2:
                raise ReplayCompletionError("invalid_replay_input_fingerprints")
            node_id, fingerprint = item
            _text(node_id, "replay_fingerprint_node_id")
            _text(fingerprint, "replay_input_fingerprint")
            if node_id in fingerprints:
                raise ReplayCompletionError("duplicate_replay_input_fingerprint")
            fingerprints[node_id] = fingerprint
        if tuple(sorted(fingerprints)) != tuple(sorted(node_ids)):
            raise ReplayCompletionError("replay_input_fingerprint_scope_mismatch")

    @classmethod
    def from_evaluated_snapshot(
        cls,
        *,
        replay_plan_id: str,
        result_graph_revision: str,
        source_snapshot: ContextGraphSnapshot,
        binding_ref: str,
        revisions: FrozenContextRevisions,
        input_fingerprints: Mapping[str, str],
    ) -> "ReplayPlan":
        """Freeze the platform evaluator's exact stale order into a plan."""

        validate_snapshot(source_snapshot)
        order = stale_replay_order(source_snapshot)
        if not order:
            raise ReplayCompletionError("replay_plan_requires_stale_nodes")
        if not isinstance(input_fingerprints, Mapping):
            raise ReplayCompletionError("invalid_replay_input_fingerprints")
        return cls(
            replay_plan_id=replay_plan_id,
            project_id=source_snapshot.project_id,
            graph_id=source_snapshot.graph_id,
            source_graph_revision=source_snapshot.graph_revision,
            result_graph_revision=result_graph_revision,
            node_ids=order,
            input_fingerprints=tuple(sorted(input_fingerprints.items())),
            binding_ref=binding_ref,
            revisions=revisions,
        )

    def input_fingerprint_for(self, node_id: str) -> str:
        for candidate, fingerprint in self.input_fingerprints:
            if candidate == node_id:
                return fingerprint
        raise ReplayCompletionError("replay_plan_node_missing")


@dataclass(frozen=True, slots=True)
class ReplayRequest:
    """One node generation request, bound to its immutable plan and input."""

    replay_request_id: str
    replay_plan_id: str
    project_id: str
    graph_id: str
    source_graph_revision: str
    result_graph_revision: str
    node_id: str
    plan_index: int
    input_fingerprint: str
    binding_ref: str
    turn_id: str
    turn_operation_id: str
    predecessor_receipt_refs: tuple[str, ...]
    revisions: FrozenContextRevisions

    def __post_init__(self) -> None:
        for field in (
            "replay_request_id", "replay_plan_id", "project_id", "graph_id",
            "source_graph_revision", "result_graph_revision", "node_id",
            "input_fingerprint", "binding_ref", "turn_id", "turn_operation_id",
        ):
            _text(getattr(self, field), field)
        if type(self.plan_index) is not int or self.plan_index < 0:
            raise ReplayCompletionError("invalid_replay_plan_index")
        _unique_texts(self.predecessor_receipt_refs, "predecessor_receipt_refs")
        if not isinstance(self.revisions, FrozenContextRevisions):
            raise ReplayCompletionError("invalid_replay_revisions")


_TERMINAL_SEAL = object()
_MODEL_WIRE_SEAL = object()


class _TrustedTerminalEvidence:
    __slots__ = ("turn_id", "turn_operation_id", "terminal_event_ref", "status", "_seal")

    def __init__(self, turn_id: str, turn_operation_id: str, terminal_event_ref: str, status: str, seal: object) -> None:
        if seal is not _TERMINAL_SEAL:
            raise TypeError("terminal replay evidence is authority-owned")
        self.turn_id = _text(turn_id, "turn_id")
        self.turn_operation_id = _text(turn_operation_id, "turn_operation_id")
        self.terminal_event_ref = _text(terminal_event_ref, "terminal_event_ref")
        self.status = _text(status, "terminal_status")
        self._seal = seal


class _TrustedModelWireEvidence:
    __slots__ = ("turn_id", "turn_operation_id", "model_wire_receipt_ref", "_seal")

    def __init__(self, turn_id: str, turn_operation_id: str, model_wire_receipt_ref: str, seal: object) -> None:
        if seal is not _MODEL_WIRE_SEAL:
            raise TypeError("model-wire replay evidence is authority-owned")
        self.turn_id = _text(turn_id, "turn_id")
        self.turn_operation_id = _text(turn_operation_id, "turn_operation_id")
        self.model_wire_receipt_ref = _text(model_wire_receipt_ref, "model_wire_receipt_ref")
        self._seal = seal


def _issue_trusted_terminal_evidence(
    turn_id: str, turn_operation_id: str, terminal_event_ref: str, status: str,
) -> _TrustedTerminalEvidence:
    """Private bridge hook; only a verified terminal completion may call this."""

    return _TrustedTerminalEvidence(turn_id, turn_operation_id, terminal_event_ref, status, _TERMINAL_SEAL)


def _issue_trusted_model_wire_evidence(
    turn_id: str, turn_operation_id: str, model_wire_receipt_ref: str,
) -> _TrustedModelWireEvidence:
    """Private bridge hook; only a durable model-wire receipt may call this."""

    return _TrustedModelWireEvidence(turn_id, turn_operation_id, model_wire_receipt_ref, _MODEL_WIRE_SEAL)


@dataclass(frozen=True, slots=True)
class TrustedCompletion:
    """Output metadata accompanied by platform-issued terminal and wire proof."""

    terminal_evidence: _TrustedTerminalEvidence
    model_wire_evidence: _TrustedModelWireEvidence
    output_ref: str
    completed_at: str

    def __post_init__(self) -> None:
        if not (
            isinstance(self.terminal_evidence, _TrustedTerminalEvidence)
            and self.terminal_evidence._seal is _TERMINAL_SEAL
            and isinstance(self.model_wire_evidence, _TrustedModelWireEvidence)
            and self.model_wire_evidence._seal is _MODEL_WIRE_SEAL
        ):
            raise ReplayCompletionError("untrusted_replay_completion_evidence")
        if self.terminal_evidence.status != "completed":
            raise ReplayCompletionError("replay_terminal_not_completed")
        if (
            self.terminal_evidence.turn_id != self.model_wire_evidence.turn_id
            or self.terminal_evidence.turn_operation_id != self.model_wire_evidence.turn_operation_id
        ):
            raise ReplayCompletionError("replay_evidence_turn_mismatch")
        _text(self.output_ref, "replay_output_ref")
        _text(self.completed_at, "replay_completed_at")


@dataclass(frozen=True, slots=True)
class NodeGenerationReceipt:
    """Immutable accepted replay completion; never a formal-object receipt."""

    receipt_ref: str
    replay_request_id: str
    replay_plan_id: str
    project_id: str
    graph_id: str
    source_graph_revision: str
    result_graph_revision: str
    node_id: str
    plan_index: int
    input_fingerprint: str
    binding_ref: str
    turn_id: str
    turn_operation_id: str
    terminal_event_ref: str
    model_wire_receipt_ref: str
    predecessor_receipt_refs: tuple[str, ...]
    output_ref: str
    accepted_at: str
    revisions: FrozenContextRevisions

    def __post_init__(self) -> None:
        _text(self.receipt_ref, "replay_receipt_ref")
        ReplayRequest(
            self.replay_request_id, self.replay_plan_id, self.project_id,
            self.graph_id, self.source_graph_revision, self.result_graph_revision,
            self.node_id, self.plan_index, self.input_fingerprint, self.binding_ref,
            self.turn_id, self.turn_operation_id,
            self.predecessor_receipt_refs, self.revisions,
        )
        _text(self.output_ref, "replay_output_ref")
        _text(self.accepted_at, "replay_accepted_at")


class ReplayRevisionAuthority(Protocol):
    """Read-only current-revision fence supplied by the platform runtime."""

    def assert_current(
        self, *, replay_plan_id: str, project_id: str, graph_id: str,
        source_graph_revision: str, binding_ref: str,
        revisions: FrozenContextRevisions,
    ) -> None: ...


class ReplayCompletionRepository(Protocol):
    """Durable implementation port for immutable accepted replay receipts."""

    def get_by_request_id(self, replay_request_id: str) -> NodeGenerationReceipt | None: ...

    def get_by_plan_node(self, replay_plan_id: str, node_id: str) -> NodeGenerationReceipt | None: ...

    def append_if_absent(self, receipt: NodeGenerationReceipt) -> NodeGenerationReceipt: ...


class InMemoryReplayCompletionRepository:
    """Reference repository used only by focused contract tests."""

    def __init__(self) -> None:
        self._by_request: dict[str, NodeGenerationReceipt] = {}
        self._by_plan_node: dict[tuple[str, str], NodeGenerationReceipt] = {}

    def get_by_request_id(self, replay_request_id: str) -> NodeGenerationReceipt | None:
        return self._by_request.get(replay_request_id)

    def get_by_plan_node(self, replay_plan_id: str, node_id: str) -> NodeGenerationReceipt | None:
        return self._by_plan_node.get((replay_plan_id, node_id))

    def append_if_absent(self, receipt: NodeGenerationReceipt) -> NodeGenerationReceipt:
        existing = self._by_request.get(receipt.replay_request_id)
        if existing is not None:
            if existing != receipt:
                raise ReplayCompletionConflict("replay_request_idempotency_conflict")
            return existing
        key = (receipt.replay_plan_id, receipt.node_id)
        existing = self._by_plan_node.get(key)
        if existing is not None:
            if existing != receipt:
                raise ReplayCompletionConflict("replay_node_completion_conflict")
            return existing
        self._by_request[receipt.replay_request_id] = receipt
        self._by_plan_node[key] = receipt
        return receipt


class ReplayCompletionAuthority:
    """Accept only exact, ordered, trusted node replay completions."""

    def __init__(self, repository: ReplayCompletionRepository, revision_authority: ReplayRevisionAuthority) -> None:
        self._repository = repository
        self._revision_authority = revision_authority

    def accept(
        self,
        *,
        plan: ReplayPlan,
        request: ReplayRequest,
        completion: TrustedCompletion,
    ) -> NodeGenerationReceipt:
        self._validate_request(plan, request)
        self._revision_authority.assert_current(
            replay_plan_id=plan.replay_plan_id,
            project_id=plan.project_id,
            graph_id=plan.graph_id,
            source_graph_revision=plan.source_graph_revision,
            binding_ref=plan.binding_ref,
            revisions=plan.revisions,
        )
        self._validate_completion(request, completion)
        expected_predecessors = self._expected_predecessors(plan, request)
        if request.predecessor_receipt_refs != expected_predecessors:
            raise ReplayCompletionError("replay_predecessor_receipts_mismatch")

        receipt = NodeGenerationReceipt(
            receipt_ref=f"replay-receipt:{request.replay_request_id}",
            replay_request_id=request.replay_request_id,
            replay_plan_id=request.replay_plan_id,
            project_id=request.project_id,
            graph_id=request.graph_id,
            source_graph_revision=request.source_graph_revision,
            result_graph_revision=request.result_graph_revision,
            node_id=request.node_id,
            plan_index=request.plan_index,
            input_fingerprint=request.input_fingerprint,
            binding_ref=request.binding_ref,
            turn_id=request.turn_id,
            turn_operation_id=request.turn_operation_id,
            terminal_event_ref=completion.terminal_evidence.terminal_event_ref,
            model_wire_receipt_ref=completion.model_wire_evidence.model_wire_receipt_ref,
            predecessor_receipt_refs=request.predecessor_receipt_refs,
            output_ref=completion.output_ref,
            accepted_at=completion.completed_at,
            revisions=request.revisions,
        )
        existing = self._repository.get_by_request_id(request.replay_request_id)
        if existing is not None:
            if existing != receipt:
                raise ReplayCompletionConflict("replay_request_idempotency_conflict")
            return existing
        return self._repository.append_if_absent(receipt)

    @staticmethod
    def _validate_request(plan: ReplayPlan, request: ReplayRequest) -> None:
        if (
            request.replay_plan_id != plan.replay_plan_id
            or request.project_id != plan.project_id
            or request.graph_id != plan.graph_id
            or request.source_graph_revision != plan.source_graph_revision
            or request.result_graph_revision != plan.result_graph_revision
            or request.binding_ref != plan.binding_ref
            or request.revisions != plan.revisions
        ):
            raise ReplayCompletionError("replay_request_plan_scope_mismatch")
        if request.plan_index >= len(plan.node_ids) or plan.node_ids[request.plan_index] != request.node_id:
            raise ReplayCompletionError("replay_request_plan_order_mismatch")
        if request.input_fingerprint != plan.input_fingerprint_for(request.node_id):
            raise ReplayCompletionError("replay_request_input_fingerprint_mismatch")

    def _expected_predecessors(self, plan: ReplayPlan, request: ReplayRequest) -> tuple[str, ...]:
        receipts: list[str] = []
        for node_id in plan.node_ids[:request.plan_index]:
            receipt = self._repository.get_by_plan_node(plan.replay_plan_id, node_id)
            if receipt is None:
                raise ReplayCompletionError("replay_predecessor_not_accepted")
            receipts.append(receipt.receipt_ref)
        return tuple(receipts)

    @staticmethod
    def _validate_completion(request: ReplayRequest, completion: TrustedCompletion) -> None:
        if completion.terminal_evidence.turn_id != request.turn_id:
            raise ReplayCompletionError("replay_terminal_turn_mismatch")
        if completion.terminal_evidence.turn_operation_id != request.turn_operation_id:
            raise ReplayCompletionError("replay_terminal_operation_mismatch")
        if completion.model_wire_evidence.turn_id != request.turn_id:
            raise ReplayCompletionError("replay_model_wire_turn_mismatch")
        if completion.model_wire_evidence.turn_operation_id != request.turn_operation_id:
            raise ReplayCompletionError("replay_model_wire_operation_mismatch")
