from __future__ import annotations

import hashlib
import os
import re
import tempfile
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from .ports import ObjectStorePort
from .runtime import ObjectStoreRevisionError
from .sqlite_uow import SQLiteStructuredRecordStore


_COLLECTION = "generated_assets"
_SCHEMA_VERSION = "1.0.0"
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_OPAQUE_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,159}$")
_NAMESPACE_ID = re.compile(r"^[a-z0-9][a-z0-9._-]{0,63}$")
_MIME_TYPES = frozenset({"image/png", "image/jpeg", "image/gif", "image/webp"})
_FORBIDDEN_PROVENANCE_TERMS = frozenset(
    {
        "prompt",
        "secret",
        "password",
        "token",
        "api_key",
        "apikey",
        "authorization",
        "endpoint",
        "url",
        "uri",
        "path",
        "location",
        "content",
    }
)


class GeneratedAssetAuthorityError(ValueError):
    """Raised when generated bytes cannot become a durable asset record."""


@dataclass(frozen=True, slots=True)
class GeneratedAssetDimensions:
    width: int
    height: int


@dataclass(frozen=True, slots=True)
class GeneratedAssetRecord:
    asset_id: str
    asset_ref: str
    vault_ref: str
    sha256: str
    byte_count: int
    media_type: str
    dimensions: GeneratedAssetDimensions
    project_id: str
    turn_id: str
    operation_id: str
    invocation_id: str
    provider_id: str
    provider_revision: str
    model_id: str
    model_revision: str
    receipt_refs: tuple[str, ...]
    provenance: Mapping[str, str | int | bool]
    status: Literal["preparing", "stored"]
    revision: int

    def as_payload(self) -> dict[str, object]:
        return {
            "schema_version": _SCHEMA_VERSION,
            "id": self.asset_id,
            "kind": "generated_asset",
            "status": self.status,
            "asset_ref": self.asset_ref,
            "vault_ref": self.vault_ref,
            "sha256": self.sha256,
            "byte_count": self.byte_count,
            "media_type": self.media_type,
            "dimensions": {
                "width": self.dimensions.width,
                "height": self.dimensions.height,
            },
            "project_id": self.project_id,
            "turn_id": self.turn_id,
            "operation_id": self.operation_id,
            "invocation_id": self.invocation_id,
            "provider_id": self.provider_id,
            "provider_revision": self.provider_revision,
            "model_id": self.model_id,
            "model_revision": self.model_revision,
            "receipt_refs": list(self.receipt_refs),
            "provenance": dict(self.provenance),
        }

    def identity_payload(self) -> dict[str, object]:
        """Return immutable generation evidence without the recovery state."""

        payload = self.as_payload()
        payload.pop("status")
        return payload


class GeneratedAssetAuthority:
    """Persist generated image bytes and their non-sensitive provenance once.

    This is deliberately distinct from ``workbench_original_assets``.  An
    original file describes user-supplied source material and its source-link
    lifecycle; this authority only accepts a verified generated image result.
    It uses the existing ObjectStore or an existing structured SQLite store and
    writes bytes below the already-selected Vault root.  It neither creates a
    database nor owns an execution Job.
    """

    max_bytes = 64 * 1024 * 1024

    def __init__(
        self,
        *,
        object_store: ObjectStorePort,
        vault_root: Path,
        namespace_id: str = "default",
        sqlite_records: SQLiteStructuredRecordStore | None = None,
    ) -> None:
        if not isinstance(namespace_id, str) or not _NAMESPACE_ID.fullmatch(namespace_id):
            raise GeneratedAssetAuthorityError("generated asset namespace_id is invalid")
        self._object_store = object_store
        self._vault_root = vault_root.expanduser().resolve(strict=False)
        self._namespace_id = namespace_id
        self._records = sqlite_records

    def store(
        self,
        *,
        content: bytes,
        sha256: str,
        media_type: str,
        dimensions: GeneratedAssetDimensions,
        project_id: str,
        turn_id: str,
        operation_id: str,
        invocation_id: str,
        provider_id: str,
        provider_revision: str,
        model_id: str,
        model_revision: str,
        receipt_refs: Sequence[str],
        provenance: Mapping[str, str | int | bool],
    ) -> GeneratedAssetRecord:
        """Prepare metadata, persist verified bytes, then CAS it to ``stored``.

        Replaying the same invocation returns the existing record without a
        second structured write.  A deterministic identity with divergent
        metadata is rejected instead of silently overwriting audit evidence.
        """

        clean_content = _content(content)
        clean_hash = _hash(sha256)
        actual_hash = hashlib.sha256(clean_content).hexdigest()
        if actual_hash != clean_hash:
            raise GeneratedAssetAuthorityError("generated asset sha256 does not match bytes")
        clean_mime = _mime(media_type)
        clean_dimensions = _dimensions(dimensions)
        actual_dimensions = _image_dimensions(clean_content, clean_mime)
        if actual_dimensions != clean_dimensions:
            raise GeneratedAssetAuthorityError("generated asset dimensions do not match image bytes")
        clean_project = _require_opaque("project_id", project_id)
        clean_turn = _require_opaque("turn_id", turn_id)
        clean_operation = _require_opaque("operation_id", operation_id)
        clean_invocation = _require_opaque("invocation_id", invocation_id)
        clean_provider = _require_opaque("provider_id", provider_id)
        clean_provider_revision = _require_opaque("provider_revision", provider_revision)
        clean_model = _require_opaque("model_id", model_id)
        clean_model_revision = _require_opaque("model_revision", model_revision)
        clean_receipts = _receipt_refs(receipt_refs)
        clean_provenance = _provenance(provenance)

        identity = "\x00".join(
            (
                clean_hash,
                clean_project,
                clean_turn,
                clean_operation,
                clean_invocation,
                clean_provider,
                clean_provider_revision,
                clean_model,
                clean_model_revision,
            )
        )
        asset_id = f"generated-{hashlib.sha256(identity.encode('utf-8')).hexdigest()[:32]}"
        vault_ref = f"assets/generated/{clean_hash[:2]}/{clean_hash}"
        asset_ref = f"crp-ref-{self._namespace_id}-assets-generated-{asset_id}"
        candidate = GeneratedAssetRecord(
            asset_id=asset_id,
            asset_ref=asset_ref,
            vault_ref=vault_ref,
            sha256=clean_hash,
            byte_count=len(clean_content),
            media_type=clean_mime,
            dimensions=clean_dimensions,
            project_id=clean_project,
            turn_id=clean_turn,
            operation_id=clean_operation,
            invocation_id=clean_invocation,
            provider_id=clean_provider,
            provider_revision=clean_provider_revision,
            model_id=clean_model,
            model_revision=clean_model_revision,
            receipt_refs=clean_receipts,
            provenance=clean_provenance,
            status="preparing",
            revision=0,
        )
        prepared = self._prepare(candidate)
        if prepared.status == "stored":
            return prepared
        self._write_blob(prepared, clean_content)
        return self._mark_stored(prepared)

    def get(self, asset_id: str) -> GeneratedAssetRecord | None:
        clean_asset_id = _require_opaque("asset_id", asset_id)
        if self._records is None:
            payload = self._object_store.read(_COLLECTION, clean_asset_id)
            return _record(payload, revision=self._object_store.revision(_COLLECTION, clean_asset_id)) if payload else None
        record = self._records.read(_COLLECTION, clean_asset_id)
        return _record(record.payload, revision=record.revision) if record else None

    def find_by_operation(
        self, *, turn_id: str, operation_id: str
    ) -> tuple[GeneratedAssetRecord, ...]:
        """Find every output of one durable operation, including preparation."""

        clean_turn = _require_opaque("turn_id", turn_id)
        clean_operation = _require_opaque("operation_id", operation_id)
        if self._records is None:
            records = tuple(
                _record(payload, revision=self._object_store.revision(_COLLECTION, str(payload.get("id") or "")))
                for payload in self._object_store.list(_COLLECTION)
                if payload.get("turn_id") == clean_turn
                and payload.get("operation_id") == clean_operation
            )
        else:
            records = tuple(
                _record(record.payload, revision=record.revision)
                for record in self._records.list(_COLLECTION)
                if record.payload.get("turn_id") == clean_turn
                and record.payload.get("operation_id") == clean_operation
            )
        return tuple(sorted(records, key=lambda item: item.asset_id))

    def reconcile(self, asset_id: str) -> GeneratedAssetRecord:
        """Recover a post-blob/pre-commit interruption without re-running a model."""

        current = self.get(asset_id)
        if current is None:
            raise GeneratedAssetAuthorityError("generated asset record was not found")
        if current.status == "stored":
            return current
        destination = self._vault_path(current.vault_ref)
        if not destination.exists():
            return current
        _verify_existing_blob(destination, current)
        return self._mark_stored(current)

    def _prepare(self, candidate: GeneratedAssetRecord) -> GeneratedAssetRecord:
        payload = candidate.as_payload()
        if self._records is None:
            existing = self._object_store.read(_COLLECTION, candidate.asset_id)
            if existing is not None:
                return _same_or_conflict(candidate, existing, self._object_store.revision(_COLLECTION, candidate.asset_id))
            try:
                revision = self._object_store.write(
                    _COLLECTION, candidate.asset_id, payload, expected_revision=0
                )
            except ObjectStoreRevisionError:
                existing = self._object_store.read(_COLLECTION, candidate.asset_id)
                if existing is None:
                    raise
                return _same_or_conflict(candidate, existing, self._object_store.revision(_COLLECTION, candidate.asset_id))
            return _record(payload, revision=revision)

        with self._records.begin() as uow:
            existing = uow.read(_COLLECTION, candidate.asset_id)
            if existing is not None:
                return _same_or_conflict(candidate, existing.payload, existing.revision)
            written = uow.put(_COLLECTION, candidate.asset_id, payload, expected_revision=0)
            uow.commit()
        return _record(payload, revision=written.revision)

    def _mark_stored(self, prepared: GeneratedAssetRecord) -> GeneratedAssetRecord:
        if prepared.status != "preparing":
            return prepared
        if self._records is None:
            current = self.get(prepared.asset_id)
            if current is None:
                raise GeneratedAssetAuthorityError("prepared generated asset record disappeared")
            _require_same_identity(prepared, current)
            if current.status == "stored":
                return current
            payload = current.as_payload()
            payload["status"] = "stored"
            try:
                revision = self._object_store.write(
                    _COLLECTION,
                    current.asset_id,
                    payload,
                    expected_revision=current.revision,
                )
            except ObjectStoreRevisionError:
                latest = self.get(current.asset_id)
                if latest is None:
                    raise
                _require_same_identity(prepared, latest)
                if latest.status == "stored":
                    return latest
                raise GeneratedAssetAuthorityError("prepared generated asset status transition conflicted")
            return _record(payload, revision=revision)

        with self._records.begin() as uow:
            current = uow.read(_COLLECTION, prepared.asset_id)
            if current is None:
                raise GeneratedAssetAuthorityError("prepared generated asset record disappeared")
            record = _record(current.payload, revision=current.revision)
            _require_same_identity(prepared, record)
            if record.status == "stored":
                return record
            payload = record.as_payload()
            payload["status"] = "stored"
            written = uow.put(
                _COLLECTION,
                record.asset_id,
                payload,
                expected_revision=record.revision,
            )
            uow.commit()
        return _record(payload, revision=written.revision)

    def _write_blob(self, prepared: GeneratedAssetRecord, content: bytes) -> None:
        _write_verified_blob(
            vault_root=self._vault_root,
            vault_ref=prepared.vault_ref,
            content=content,
            sha256=prepared.sha256,
        )

    def _vault_path(self, vault_ref: str) -> Path:
        destination = (self._vault_root / Path(*vault_ref.split("/"))).resolve(strict=False)
        try:
            destination.relative_to(self._vault_root)
        except ValueError as exc:  # pragma: no cover - vault_ref is normalized
            raise GeneratedAssetAuthorityError("generated asset vault reference escaped root") from exc
        return destination


def _same_or_conflict(
    candidate: GeneratedAssetRecord,
    existing_payload: Mapping[str, object],
    revision: int,
) -> GeneratedAssetRecord:
    existing = _record(existing_payload, revision=revision)
    _require_same_identity(candidate, existing)
    return existing


def _require_same_identity(
    candidate: GeneratedAssetRecord, existing: GeneratedAssetRecord
) -> None:
    if existing.identity_payload() != candidate.identity_payload():
        raise GeneratedAssetAuthorityError("generated asset identity conflicts with existing record")


def _content(value: bytes) -> bytes:
    if not isinstance(value, bytes) or not value:
        raise GeneratedAssetAuthorityError("generated asset content must be non-empty bytes")
    if len(value) > GeneratedAssetAuthority.max_bytes:
        raise GeneratedAssetAuthorityError("generated asset exceeds local storage limit")
    return value


def _hash(value: str) -> str:
    if not isinstance(value, str) or not _SHA256.fullmatch(value):
        raise GeneratedAssetAuthorityError("generated asset sha256 is invalid")
    return value


def _mime(value: str) -> str:
    if not isinstance(value, str) or value.lower() not in _MIME_TYPES:
        raise GeneratedAssetAuthorityError("generated asset media_type is unsupported")
    return value.lower()


def _dimensions(value: GeneratedAssetDimensions) -> GeneratedAssetDimensions:
    if not isinstance(value, GeneratedAssetDimensions):
        raise GeneratedAssetAuthorityError("generated asset dimensions are required")
    if (
        not isinstance(value.width, int)
        or isinstance(value.width, bool)
        or not isinstance(value.height, int)
        or isinstance(value.height, bool)
        or not 1 <= value.width <= 65_535
        or not 1 <= value.height <= 65_535
    ):
        raise GeneratedAssetAuthorityError("generated asset dimensions are invalid")
    return value


def _require_opaque(label: str, value: str) -> str:
    if not isinstance(value, str) or not _OPAQUE_ID.fullmatch(value):
        raise GeneratedAssetAuthorityError(f"generated asset {label} must be an opaque identifier")
    return value


def _receipt_refs(value: Sequence[str]) -> tuple[str, ...]:
    if not isinstance(value, Sequence) or isinstance(value, (str, bytes)) or not value:
        raise GeneratedAssetAuthorityError("generated asset receipt_refs are required")
    refs = tuple(_require_opaque("receipt_ref", item) for item in value)
    if len(refs) != len(set(refs)):
        raise GeneratedAssetAuthorityError("generated asset receipt_refs must be unique")
    return refs


def _provenance(value: Mapping[str, str | int | bool]) -> Mapping[str, str | int | bool]:
    if not isinstance(value, Mapping):
        raise GeneratedAssetAuthorityError("generated asset provenance must be a mapping")
    clean: dict[str, str | int | bool] = {}
    for key, item in value.items():
        if not isinstance(key, str) or not re.fullmatch(r"[a-z][a-z0-9_]{0,63}", key):
            raise GeneratedAssetAuthorityError("generated asset provenance key is invalid")
        if any(term in key for term in _FORBIDDEN_PROVENANCE_TERMS):
            raise GeneratedAssetAuthorityError("generated asset provenance contains sensitive data")
        if not isinstance(item, (str, int, bool)) or isinstance(item, float):
            raise GeneratedAssetAuthorityError("generated asset provenance value is invalid")
        if isinstance(item, str):
            if len(item) > 256 or _looks_like_forbidden_location(item):
                raise GeneratedAssetAuthorityError("generated asset provenance value is unsafe")
        clean[key] = item
    return clean


def _looks_like_forbidden_location(value: str) -> bool:
    lower = value.lower()
    return (
        "://" in lower
        or lower.startswith("file:")
        or bool(re.match(r"^[a-z]:[\\/]", value, flags=re.IGNORECASE))
        or value.startswith("/")
        or value.startswith("\\")
    )


def _write_verified_blob(*, vault_root: Path, vault_ref: str, content: bytes, sha256: str) -> None:
    destination = (vault_root / Path(*vault_ref.split("/"))).resolve(strict=False)
    try:
        destination.relative_to(vault_root)
    except ValueError as exc:  # pragma: no cover - vault_ref is internally fixed
        raise GeneratedAssetAuthorityError("generated asset vault reference escaped root") from exc
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        _verify_blob_identity(path=destination, byte_count=len(content), sha256=sha256)
        return
    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=".generated-asset-", suffix=".tmp", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(file_descriptor, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        if temporary.stat().st_size != len(content) or _file_hash(temporary) != sha256:
            raise GeneratedAssetAuthorityError("generated asset temporary bytes failed verification")
        try:
            os.replace(temporary, destination)
        except FileExistsError:
            # A concurrent identical write won the race. Verify its bytes below.
            pass
        _verify_blob_identity(path=destination, byte_count=len(content), sha256=sha256)
    finally:
        temporary.unlink(missing_ok=True)


def _file_hash(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(256 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _verify_existing_blob(path: Path, record: GeneratedAssetRecord) -> None:
    _verify_blob_identity(path=path, byte_count=record.byte_count, sha256=record.sha256)
    try:
        actual_dimensions = _image_dimensions(path.read_bytes(), record.media_type)
    except OSError as exc:
        raise GeneratedAssetAuthorityError("generated asset blob cannot be read for reconciliation") from exc
    if actual_dimensions != record.dimensions:
        raise GeneratedAssetAuthorityError("generated asset blob dimensions drifted during reconciliation")


def _verify_blob_identity(*, path: Path, byte_count: int, sha256: str) -> None:
    if not path.is_file() or path.stat().st_size != byte_count:
        raise GeneratedAssetAuthorityError("generated asset blob identity conflicts with existing bytes")
    if _file_hash(path) != sha256:
        raise GeneratedAssetAuthorityError("generated asset blob hash conflicts with existing bytes")


def _image_dimensions(content: bytes, media_type: str) -> GeneratedAssetDimensions:
    if media_type == "image/png":
        if len(content) < 24 or content[:8] != b"\x89PNG\r\n\x1a\n" or content[12:16] != b"IHDR":
            raise GeneratedAssetAuthorityError("generated PNG bytes are invalid")
        return GeneratedAssetDimensions(
            width=int.from_bytes(content[16:20], "big"),
            height=int.from_bytes(content[20:24], "big"),
        )
    if media_type == "image/gif":
        if len(content) < 10 or content[:6] not in {b"GIF87a", b"GIF89a"}:
            raise GeneratedAssetAuthorityError("generated GIF bytes are invalid")
        return GeneratedAssetDimensions(
            width=int.from_bytes(content[6:8], "little"),
            height=int.from_bytes(content[8:10], "little"),
        )
    if media_type == "image/jpeg":
        return _jpeg_dimensions(content)
    return _webp_dimensions(content)


def _jpeg_dimensions(content: bytes) -> GeneratedAssetDimensions:
    if len(content) < 4 or content[:2] != b"\xff\xd8":
        raise GeneratedAssetAuthorityError("generated JPEG bytes are invalid")
    index = 2
    while index + 9 <= len(content):
        if content[index] != 0xFF:
            index += 1
            continue
        while index < len(content) and content[index] == 0xFF:
            index += 1
        if index >= len(content):
            break
        marker = content[index]
        index += 1
        if marker in {0xD8, 0xD9}:
            continue
        if index + 2 > len(content):
            break
        length = int.from_bytes(content[index:index + 2], "big")
        if length < 2 or index + length > len(content):
            break
        if marker in {0xC0, 0xC1, 0xC2, 0xC3, 0xC5, 0xC6, 0xC7, 0xC9, 0xCA, 0xCB, 0xCD, 0xCE, 0xCF}:
            return GeneratedAssetDimensions(
                width=int.from_bytes(content[index + 5:index + 7], "big"),
                height=int.from_bytes(content[index + 3:index + 5], "big"),
            )
        index += length
    raise GeneratedAssetAuthorityError("generated JPEG dimensions are unavailable")


def _webp_dimensions(content: bytes) -> GeneratedAssetDimensions:
    if len(content) < 30 or content[:4] != b"RIFF" or content[8:12] != b"WEBP":
        raise GeneratedAssetAuthorityError("generated WEBP bytes are invalid")
    chunk = content[12:16]
    if chunk == b"VP8X":
        return GeneratedAssetDimensions(
            width=int.from_bytes(content[24:27], "little") + 1,
            height=int.from_bytes(content[27:30], "little") + 1,
        )
    if chunk == b"VP8L" and len(content) >= 25 and content[20] == 0x2F:
        bits = int.from_bytes(content[21:25], "little")
        return GeneratedAssetDimensions(width=(bits & 0x3FFF) + 1, height=((bits >> 14) & 0x3FFF) + 1)
    if chunk == b"VP8 " and len(content) >= 30 and content[23:26] == b"\x9d\x01\x2a":
        return GeneratedAssetDimensions(
            width=int.from_bytes(content[26:28], "little") & 0x3FFF,
            height=int.from_bytes(content[28:30], "little") & 0x3FFF,
        )
    raise GeneratedAssetAuthorityError("generated WEBP dimensions are unavailable")


def _record(payload: Mapping[str, object], *, revision: int) -> GeneratedAssetRecord:
    if (
        not isinstance(payload, Mapping)
        or payload.get("schema_version") != _SCHEMA_VERSION
        or payload.get("kind") != "generated_asset"
    ):
        raise GeneratedAssetAuthorityError("stored generated asset record is invalid")
    dimensions = payload.get("dimensions")
    if not isinstance(dimensions, Mapping):
        raise GeneratedAssetAuthorityError("stored generated asset dimensions are invalid")
    result = GeneratedAssetRecord(
        asset_id=_require_opaque("asset_id", payload.get("id")),
        asset_ref=_asset_ref(payload.get("asset_ref")),
        vault_ref=_safe_vault_ref(payload.get("vault_ref")),
        sha256=_hash(payload.get("sha256")),
        byte_count=_byte_count(payload.get("byte_count")),
        media_type=_mime(payload.get("media_type")),
        dimensions=_dimensions(GeneratedAssetDimensions(dimensions.get("width"), dimensions.get("height"))),
        project_id=_require_opaque("project_id", payload.get("project_id")),
        turn_id=_require_opaque("turn_id", payload.get("turn_id")),
        operation_id=_require_opaque("operation_id", payload.get("operation_id")),
        invocation_id=_require_opaque("invocation_id", payload.get("invocation_id")),
        provider_id=_require_opaque("provider_id", payload.get("provider_id")),
        provider_revision=_require_opaque("provider_revision", payload.get("provider_revision")),
        model_id=_require_opaque("model_id", payload.get("model_id")),
        model_revision=_require_opaque("model_revision", payload.get("model_revision")),
        receipt_refs=_receipt_refs(payload.get("receipt_refs")),
        provenance=_provenance(payload.get("provenance")),
        status=_status(payload.get("status")),
        revision=revision,
    )
    if not re.fullmatch(
        rf"crp-ref-[a-z0-9][a-z0-9._-]{{0,63}}-assets-generated-{re.escape(result.asset_id)}",
        result.asset_ref,
    ):
        raise GeneratedAssetAuthorityError("stored generated asset ref is invalid")
    if result.vault_ref != f"assets/generated/{result.sha256[:2]}/{result.sha256}":
        raise GeneratedAssetAuthorityError("stored generated asset vault ref is invalid")
    return result


def _byte_count(value: object) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or not 1 <= value <= GeneratedAssetAuthority.max_bytes:
        raise GeneratedAssetAuthorityError("stored generated asset byte_count is invalid")
    return value


def _status(value: object) -> Literal["preparing", "stored"]:
    if value not in {"preparing", "stored"}:
        raise GeneratedAssetAuthorityError("stored generated asset status is invalid")
    return value


def _safe_vault_ref(value: object) -> str:
    if not isinstance(value, str) or not re.fullmatch(r"assets/generated/[0-9a-f]{2}/[0-9a-f]{64}", value):
        raise GeneratedAssetAuthorityError("stored generated asset vault_ref is invalid")
    return value


def _asset_ref(value: object) -> str:
    if not isinstance(value, str) or not re.fullmatch(
        r"crp-ref-[a-z0-9][a-z0-9._-]{0,63}-assets-generated-generated-[0-9a-f]{32}",
        value,
    ):
        raise GeneratedAssetAuthorityError("stored generated asset asset_ref is invalid")
    return value
