"""Persistent job orchestration ports."""

from .ports import JobHandlerPort, JobRepositoryPort, JobStepBlockedError, JobStepResult
from .admission import JobAdmissionAuthorization, JobAdmissionCommandKind
from .effect_commands import JobCancellationResult, SQLiteJobEffectCommandAuthority
from .execution_admission import JobExecutionAdmission, JobExecutionAdmissionAuthority
from .sqlite_admission import JobAdmissionPreflight, SQLiteJobAdmissionCommand
from .job_projection import (
    JobEffectProjectionAuthority,
    JobProjectionBuilder,
    JobProjectionRecord,
    initialize_job_projection_schema,
    job_attempt_operation_id,
    job_execution_operation_id,
    job_root_operation_id,
    job_step_operation_id,
)
from .legacy_history import (
    LegacyJobHistoryProjection,
    LegacyJobHistoryRecord,
    LegacyJobHistorySnapshot,
    initialize_legacy_job_history_schema,
    legacy_job_history_display_payload,
    legacy_job_readonly_payload,
)
from .history_governance import (
    ExplicitRebuildLink,
    GovernanceAction,
    HistoryCategory,
    HistoryGovernanceDisplay,
    HistoryGovernanceDryRun,
    HistoryMetadata,
    build_history_governance_dry_run,
    plan_explicit_rebuild,
    scan_history_metadata_in_connection,
    scan_vault_history_metadata,
)
from .media_recipe_step_evidence import (
    MediaRecipeStepEvidence,
    can_transition_media_recipe_step_evidence,
    media_recipe_step_evidence_from_payload,
    media_recipe_step_evidence_to_payload,
    transition_media_recipe_step_evidence,
    validate_media_recipe_step_evidence,
)
from .media_recipe_step_receipt import (
    MediaRecipeStepReceipt,
    media_recipe_step_receipt_from_payload,
    media_recipe_step_receipt_to_payload,
    validate_media_recipe_step_receipt,
)
from .runtime import InMemoryJobRepository, ObjectStoreJobRepository
from .routed_repository import JobAuthorityConflict, RoutedJobRepository
from .sqlite_store import (
    SQLiteJobLeaseConflict,
    SQLiteJobRecord,
    SQLiteJobStore,
    SQLiteJobStoreTransaction,
    SQLiteLegacyMediaExecutionBlocked,
    SQLiteMediaAdmissionConflict,
    SQLiteMediaConcurrencyConflict,
)
from .source_job_memory_uow import (
    SQLiteSourceJobMemoryCommit,
    SQLiteSourceJobMemoryTransaction,
    SQLiteSourceJobMemoryUnitOfWork,
    SQLiteSourceJobMemoryUnitOfWorkError,
)
from .source_job_memory_migration import (
    SourceJobMemoryMigrationExecutionError,
    SourceJobMemoryMigrationExecutionResult,
    SourceJobMemoryMigrationInventory,
    SourceJobMemoryMigrationInventoryError,
    SourceJobMemoryMigrationIssue,
    execute_source_job_memory_fixture_migration,
    plan_source_job_memory_migration_dry_run,
    scan_source_job_memory_migration_inventory,
)
from .sqlite_lifecycle import SQLiteJobRuntimeLifecycle
from .service import JobCancelService, JobRetryService, JobServiceError, JobStatusService
from .status import (
    BLOCKED_REASONS,
    BLOCKED_REASON_AUTHORIZATION_REQUIRED,
    BLOCKED_REASON_NETWORK_RETRYABLE,
    BLOCKED_REASON_PATH_UNAVAILABLE,
    BLOCKED_REASON_PROVIDER_MISSING,
    BLOCKED_REASON_SCHEMA_REJECTED,
    BLOCKED_REASON_USER_CONFIRMATION_REQUIRED,
    JOB_RETRYABLE_STATUSES,
    JOB_STATUSES,
    JOB_STATUS_CANCELLED,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
    JOB_STATUS_PENDING,
    JOB_STATUS_RUNNING,
    JOB_STATUS_WAITING_USER,
    STEP_RETRYABLE_STATUSES,
    STEP_STATUSES,
    STEP_STATUS_CANCELLED,
    STEP_STATUS_COMPLETED,
    STEP_STATUS_FAILED,
    STEP_STATUS_PENDING,
    STEP_STATUS_RUNNING,
    STEP_STATUS_SKIPPED,
    STEP_STATUS_WAITING_USER,
    STEP_TERMINAL_OK_STATUSES,
    is_retryable_job_status,
    is_retryable_step_status,
)

__all__ = [
    "BLOCKED_REASONS",
    "BLOCKED_REASON_AUTHORIZATION_REQUIRED",
    "BLOCKED_REASON_NETWORK_RETRYABLE",
    "BLOCKED_REASON_PATH_UNAVAILABLE",
    "BLOCKED_REASON_PROVIDER_MISSING",
    "BLOCKED_REASON_SCHEMA_REJECTED",
    "BLOCKED_REASON_USER_CONFIRMATION_REQUIRED",
    "InMemoryJobRepository",
    "JOB_RETRYABLE_STATUSES",
    "JobRetryService",
    "JobCancelService",
    "JobServiceError",
    "JobStatusService",
    "JobStepBlockedError",
    "JobStepResult",
    "JOB_STATUSES",
    "JOB_STATUS_CANCELLED",
    "JOB_STATUS_COMPLETED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_PENDING",
    "JOB_STATUS_RUNNING",
    "JOB_STATUS_WAITING_USER",
    "JobHandlerPort",
    "JobAdmissionAuthorization",
    "JobAdmissionCommandKind",
    "JobCancellationResult",
    "JobExecutionAdmission",
    "JobExecutionAdmissionAuthority",
    "JobAdmissionPreflight",
    "JobEffectProjectionAuthority",
    "JobProjectionBuilder",
    "JobProjectionRecord",
    "JobAuthorityConflict",
    "JobRepositoryPort",
    "LegacyJobHistoryProjection",
    "LegacyJobHistoryRecord",
    "LegacyJobHistorySnapshot",
    "ExplicitRebuildLink",
    "GovernanceAction",
    "HistoryCategory",
    "HistoryGovernanceDisplay",
    "HistoryGovernanceDryRun",
    "HistoryMetadata",
    "MediaRecipeStepEvidence",
    "MediaRecipeStepReceipt",
    "ObjectStoreJobRepository",
    "RoutedJobRepository",
    "SQLiteJobLeaseConflict",
    "SQLiteLegacyMediaExecutionBlocked",
    "SQLiteJobAdmissionCommand",
    "SQLiteJobEffectCommandAuthority",
    "SQLiteMediaAdmissionConflict",
    "SQLiteMediaConcurrencyConflict",
    "SQLiteJobRuntimeLifecycle",
    "SQLiteJobRecord",
    "SQLiteJobStore",
    "SQLiteJobStoreTransaction",
    "SQLiteSourceJobMemoryCommit",
    "SQLiteSourceJobMemoryTransaction",
    "SQLiteSourceJobMemoryUnitOfWork",
    "SQLiteSourceJobMemoryUnitOfWorkError",
    "SourceJobMemoryMigrationExecutionError",
    "SourceJobMemoryMigrationExecutionResult",
    "SourceJobMemoryMigrationInventory",
    "SourceJobMemoryMigrationInventoryError",
    "SourceJobMemoryMigrationIssue",
    "STEP_RETRYABLE_STATUSES",
    "STEP_STATUSES",
    "STEP_STATUS_CANCELLED",
    "STEP_STATUS_COMPLETED",
    "STEP_STATUS_FAILED",
    "STEP_STATUS_PENDING",
    "STEP_STATUS_RUNNING",
    "STEP_STATUS_SKIPPED",
    "STEP_STATUS_WAITING_USER",
    "STEP_TERMINAL_OK_STATUSES",
    "is_retryable_job_status",
    "is_retryable_step_status",
    "initialize_job_projection_schema",
    "initialize_legacy_job_history_schema",
    "job_attempt_operation_id",
    "job_execution_operation_id",
    "job_root_operation_id",
    "job_step_operation_id",
    "legacy_job_history_display_payload",
    "legacy_job_readonly_payload",
    "build_history_governance_dry_run",
    "plan_explicit_rebuild",
    "scan_history_metadata_in_connection",
    "scan_vault_history_metadata",
    "execute_source_job_memory_fixture_migration",
    "plan_source_job_memory_migration_dry_run",
    "scan_source_job_memory_migration_inventory",
    "can_transition_media_recipe_step_evidence",
    "media_recipe_step_evidence_from_payload",
    "media_recipe_step_evidence_to_payload",
    "media_recipe_step_receipt_from_payload",
    "media_recipe_step_receipt_to_payload",
    "transition_media_recipe_step_evidence",
    "validate_media_recipe_step_evidence",
    "validate_media_recipe_step_receipt",
]
