"""Provider-neutral AI kernel contracts and ports.

The package owns turn orchestration contracts. Domain data authority remains in
Library, Memory, Project Skill, Document, Job, and platform modules.
"""

from .agent_contracts import (
    AgentBudget,
    AgentBudgetReservation,
    AgentChildLink,
    AgentContractError,
    AgentFanIn,
    AgentFanInResult,
    AgentMessage,
    AgentProfile,
    AgentRun,
    AgentTerminalChildSummary,
    validate_child_delegation,
    validate_fan_in_result,
)
from .agent_profiles import (
    AgentProfileConflict,
    AgentProfileError,
    AgentProfileRegistry,
    AgentProfileTierResolution,
    InMemoryAgentProfileStore,
    builtin_agent_profiles,
)
from .agent_store import (
    AgentStoreConflict,
    AgentStoreError,
    AgentStoreInvalidTransition,
    AgentStoreLimitExceeded,
    AgentStoreNotFound,
    AgentStoreStaleEpoch,
    SQLiteAgentStore,
)
from .contracts import (
    AIKernelContractError,
    TERMINAL_EVENT_TYPES,
    validate_capability_manifest,
    validate_event_transition,
    validate_governed_payload,
    validate_model_dispatch_authority_receipt,
    validate_model_wire_attempt_receipt,
    validate_prompt_cache_receipt,
    validate_turn_action,
    validate_turn_presentation_artifact,
    validate_turn_request,
)
from .ports import (
    AgentPlannerPort,
    ExpertTurnBindingPort,
    AIRuntimePort,
    CapabilityDefinition,
    CapabilityManifest,
    CapabilityManifestResolverPort,
    ContextCompaction,
    ContextEntry,
    ContextManifest,
    ContextManifestResolverPort,
    ToolExecutionBoundaryDecision,
    ToolExecutionBoundaryPort,
    ToolDispatcherPort,
    ToolDispatchObserverPort,
    CapabilityProviderPort,
    CapabilityRegistrationPort,
    CapabilityRegistryPort,
    TurnEventStorePort,
    TurnPayloadStorePort,
    TurnStateStorePort,
    TurnReceipt,
    RunLeaseRecord,
    RunLeaseRecoveryDisposition,
    RunLeaseStatus,
    RunLeaseToken,
    RecoveryDecision,
    RecoveryQueueItem,
    PublicRecoveryReview,
    RecoveryReviewAuthorization,
    RecoveryDisposition,
    validate_recovery_decision,
    validate_recovery_queue_item,
    validate_public_recovery_review,
    validate_recovery_review_authorization,
    validate_recovery_review_identity,
    TurnStatus,
)
from .capability_manifest import (
    CapabilityManifestError,
    V1TurnPolicyCapabilityManifestResolver,
    manifest_from_payload,
    manifest_to_payload,
)
from .context_manifest import (
    ContextManifestError,
    V1TurnContextManifestResolver,
    context_manifest_from_payload,
    context_manifest_to_payload,
    context_payload_refs,
    validate_context_manifest_for_request,
)
from .context_entries import (
    TypedContextEntryError,
    record_typed_context_entry,
    typed_context_model_projection,
    typed_context_raw_result,
)
from .event_store import InMemoryTurnEventStore, RunLeaseRevoked, TurnEventConflict
from .external_agent_context import (
    AgentAdapterProfile,
    ExternalAgentAdmissionSnapshot,
    ExternalAgentAuthoritySnapshot,
    ExternalAgentContextBridge,
    ExternalAgentContextConflict,
    ExternalAgentCursorGap,
    ExternalAgentContextError,
    validate_external_agent_safe_projection,
)
from .external_agent_client_adapters import (
    ClientAdapterMutation,
    ClientAdapterTemplate,
    ExternalAgentClientAdapterConflict,
    ExternalAgentClientAdapterError,
    generate_client_templates,
    install as install_external_agent_client_adapter,
    preview_install as preview_external_agent_client_adapter_install,
    preview_uninstall as preview_external_agent_client_adapter_uninstall,
    uninstall as uninstall_external_agent_client_adapter,
)
from .execution_projection import ExecutionProjectionView, build_execution_projection, validate_execution_projection
from .dispatcher import (
    SynchronousToolDispatcher,
    ToolCancellationToken,
    ToolDispatchCancelled,
    ToolDispatchDeadlineExceeded,
    ToolDispatchFailure,
    ToolDispatchRequest,
    ToolDispatcherError,
    ToolExecutionContext,
    NestedModelHandleUnavailable,
    ToolProviderFailure,
)
from .memory_recall import MemoryRecallCapability
from .model_planner import ModelGatewayAgentPlanner, ModelPlannerError
from .payload_store import InMemoryTurnPayloadStore, TurnPayloadNotFound
from .registry import CapabilityRegistryError, CapabilityRegistrySnapshot, ScopedCapabilityRegistry
from .runtime import AIKernelRuntimeError, SynchronousAIRuntime
from .recovery import classify_recovery
from .sqlite_store import SQLiteAITurnStore
from .state_store import InMemoryTurnStateStore, TurnStateConflict
from .scoped_payloads import ScopedTurnPayloadError, ScopedTurnPayloadView, event_payload_refs, planner_context_payload_refs
from .codex_hook_runtime import (
    CodexHookHost,
    HookAuditOutbox,
    HookAuditObservation,
    HookHandlerManifest,
    HookInvocationReceipt,
    HookPolicyCatalog,
    HookPolicySnapshot,
    HookRuntimeError,
    HookRuntimeMetrics,
    LocalHookHandlerRunner,
    RevisionPinnedHookRunner,
    hook_invocation_receipt_to_payload,
    hook_policy_snapshot_from_payload,
    hook_policy_snapshot_to_payload,
    policy_snapshot_from_payload,
    policy_snapshot_to_payload,
    receipt_to_payload,
)

__all__ = [
    "AgentBudget",
    "AgentBudgetReservation",
    "AgentChildLink",
    "AgentContractError",
    "AgentFanIn",
    "AgentFanInResult",
    "AgentMessage",
    "AgentPlannerPort",
    "AgentProfile",
    "AgentProfileConflict",
    "AgentProfileError",
    "AgentProfileRegistry",
    "AgentProfileTierResolution",
    "AgentRun",
    "AgentStoreConflict",
    "AgentStoreError",
    "AgentStoreInvalidTransition",
    "AgentStoreLimitExceeded",
    "AgentStoreNotFound",
    "AgentStoreStaleEpoch",
    "AgentTerminalChildSummary",
    "ExpertTurnBindingPort",
    "AIKernelContractError",
    "AIKernelRuntimeError",
    "AIRuntimePort",
    "CapabilityDefinition",
    "CapabilityManifest",
    "CapabilityManifestError",
    "CapabilityManifestResolverPort",
    "ContextCompaction",
    "ContextEntry",
    "ContextManifest",
    "ContextManifestError",
    "ContextManifestResolverPort",
    "TypedContextEntryError",
    "ExecutionProjectionView",
    "AgentAdapterProfile",
    "ExternalAgentAuthoritySnapshot",
    "ExternalAgentContextBridge",
    "ExternalAgentContextConflict",
    "ExternalAgentCursorGap",
    "ExternalAgentContextError",
    "validate_external_agent_safe_projection",
    "ClientAdapterMutation",
    "ClientAdapterTemplate",
    "ExternalAgentClientAdapterConflict",
    "ExternalAgentClientAdapterError",
    "generate_client_templates",
    "install_external_agent_client_adapter",
    "preview_external_agent_client_adapter_install",
    "preview_external_agent_client_adapter_uninstall",
    "uninstall_external_agent_client_adapter",
    "ToolExecutionBoundaryDecision",
    "ToolExecutionBoundaryPort",
    "ToolDispatcherPort",
    "ToolDispatchObserverPort",
    "ToolDispatchRequest",
    "ToolDispatchCancelled",
    "ToolDispatchDeadlineExceeded",
    "ToolDispatchFailure",
    "ToolDispatcherError",
    "ToolCancellationToken",
    "ToolExecutionContext",
    "NestedModelHandleUnavailable",
    "ToolProviderFailure",
    "CapabilityProviderPort",
    "CapabilityRegistrationPort",
    "CapabilityRegistryError",
    "CapabilityRegistrySnapshot",
    "CapabilityRegistryPort",
    "InMemoryAgentProfileStore",
    "InMemoryTurnEventStore",
    "InMemoryTurnPayloadStore",
    "InMemoryTurnStateStore",
    "MemoryRecallCapability",
    "ModelGatewayAgentPlanner",
    "ModelPlannerError",
    "ScopedCapabilityRegistry",
    "ScopedTurnPayloadError",
    "ScopedTurnPayloadView",
    "SynchronousAIRuntime",
    "SynchronousToolDispatcher",
    "SQLiteAITurnStore",
    "SQLiteAgentStore",
    "TERMINAL_EVENT_TYPES",
    "TurnEventConflict",
    "RunLeaseRevoked",
    "TurnEventStorePort",
    "TurnPayloadNotFound",
    "TurnPayloadStorePort",
    "TurnStateConflict",
    "TurnStateStorePort",
    "TurnReceipt",
    "RunLeaseRecord",
    "RunLeaseRecoveryDisposition",
    "RunLeaseStatus",
    "RunLeaseToken",
    "RecoveryDecision",
    "RecoveryQueueItem",
    "PublicRecoveryReview",
    "RecoveryReviewAuthorization",
    "RecoveryDisposition",
    "validate_recovery_decision",
    "validate_recovery_queue_item",
    "validate_public_recovery_review",
    "validate_recovery_review_authorization",
    "validate_recovery_review_identity",
    "TurnStatus",
    "V1TurnPolicyCapabilityManifestResolver",
    "V1TurnContextManifestResolver",
    "context_manifest_from_payload",
    "context_manifest_to_payload",
    "context_payload_refs",
    "record_typed_context_entry",
    "typed_context_model_projection",
    "typed_context_raw_result",
    "manifest_from_payload",
    "manifest_to_payload",
    "validate_capability_manifest",
    "validate_event_transition",
    "validate_governed_payload",
    "validate_model_dispatch_authority_receipt",
    "validate_model_wire_attempt_receipt",
    "validate_prompt_cache_receipt",
    "validate_turn_action",
    "validate_turn_presentation_artifact",
    "validate_turn_request",
    "event_payload_refs",
    "planner_context_payload_refs",
    "validate_child_delegation",
    "validate_context_manifest_for_request",
    "validate_fan_in_result",
    "build_execution_projection",
    "builtin_agent_profiles",
    "classify_recovery",
    "validate_execution_projection",
    "CodexHookHost",
    "HookAuditOutbox",
    "HookAuditObservation",
    "HookHandlerManifest",
    "HookInvocationReceipt",
    "HookPolicyCatalog",
    "HookPolicySnapshot",
    "HookRuntimeError",
    "HookRuntimeMetrics",
    "LocalHookHandlerRunner",
    "RevisionPinnedHookRunner",
    "hook_invocation_receipt_to_payload",
    "hook_policy_snapshot_from_payload",
    "hook_policy_snapshot_to_payload",
    "policy_snapshot_from_payload",
    "policy_snapshot_to_payload",
    "receipt_to_payload",
]
