"""Platform-neutral Companion domain contracts and persistence services."""

from .backup import CompanionBackupService
from .clock import CompanionClock, FixedCompanionClock, SystemCompanionClock, build_companion_clock
from .chat import CompanionChatCancelled, CompanionChatError, CompanionChatService
from .character_prompt import DEFAULT_CHARACTER_PROMPT, DEFAULT_CHARACTER_PROMPT_REVISION, default_character_prompt
from .history import CompanionHardForgetError, CompanionHistoryService
from .conversation_recall import ConversationRecall, ConversationRecallService
from .memory_bridge import (
    CompanionMemoryBridge,
    CompanionMemoryBridgeError,
    CompanionMemoryCandidateResult,
    CompanionMemoryRecall,
)
from .memory_vector_evaluation import (
    CompanionMemoryEvaluationError,
    EvaluationCorpus,
    EvaluationDocument,
    EvaluationMetrics,
    EvaluationQuery,
    RetrievalHit,
    decision,
    evaluate_fts5_baseline,
    evaluate_retriever,
    evaluate_vector_embeddings,
    hybrid_hits,
    load_evaluation_corpus,
)
from .errors import (
    CompanionConflict,
    CompanionIntegrityError,
    CompanionRepositoryError,
    CompanionRestoreConflict,
    CompanionSchemaTooNew,
)
from .models import (
    CompanionBackupReceipt,
    CompanionChatResult,
    CompanionForgetReceipt,
    CompanionHistoryItem,
    CompanionHistoryPage,
    CompanionInventoryItem,
    CompanionInteractionEvent,
    CompanionMasterProfile,
    CompanionMessage,
    CompanionMessageDependency,
    CompanionMessagePage,
    ConversationEpisodeProjection,
    CompanionReminder,
    CompanionReminderOccurrence,
    CompanionProfileMutation,
    CompanionPromptBinding,
    CompanionPromptBindingMutation,
    CompanionRestorePreflight,
    CompanionRestoreReceipt,
    CompanionSchemaStatus,
    CompanionSetting,
    CompanionSession,
    CompanionStateActionResult,
    CompanionStateSnapshot,
    CompanionStateProjection,
    CompanionWalletEntry,
    CompanionWalletIntegrity,
    CompanionWalletMutation,
)
from .repository import CompanionRepository
from .profile import (
    CharacterPromptMutation,
    CompanionProfileService,
    PromptActivationChange,
    PromptSnapshot,
    validate_profile_input,
    validate_prompt_content,
)
from .notes import (
    CompanionManualService,
    CompanionNote,
    CompanionNotesService,
    ManualAuthority,
)
from .scheduler import (
    CompanionEvent,
    CompanionScheduler,
    EventPriority,
    InMemorySchedulerStore,
    ScheduledTrigger,
    SchedulerMode,
)
from .routine import CompanionRoutineService, CompanionRoutineSnapshot, DEFAULT_ROUTINE, validate_routine_settings
from .reminders import CompanionReminderService, hourly_key, hourly_text, make_hourly_event
from .model_routes import (
    CHARACTER_PROMPT_ID,
    COMPANION_ROUTE_KEYS,
    ROUTE_POLICIES,
    CompanionModelRouteError,
    CompanionModelRouter,
    CompanionProviderCancelled,
    CompanionProviderFailure,
    CompanionProviderTimeout,
    CompanionRoutePolicy,
    ComposedPrompt,
    compose_companion_prompt,
    require_route_policy,
    trace_contains_sensitive_body,
)
from .provider_contract import companion_provider_instruction, parse_companion_chat_envelope
from .vision import CompanionVisionGrantStore, CompanionVisionService, MAX_VISION_BYTES, clean_stale_vision_grants
from .voice_call import CompanionVoiceGrantStore, CompanionVoiceTranscriptionService, MAX_VOICE_AUDIO_BYTES, clean_stale_voice_grants
from .schema import SCHEMA_VERSION
from .state import CompanionStateReducer, EconomyRules, StateRule, companion_chat_state_context, load_economy_rules
from .commerce import CompanionCatalog, CompanionCommerceService, CatalogItem, ShopOffer, load_catalog
from .appearance import CompanionAppearanceCatalog, CompanionAppearanceService, load_appearance_catalog
from .focus import CompanionFocusService, FocusSnapshot, normalize_process_name, sample_foreground_process
from .ambient import CompanionAmbientService
from .diary import CompanionDiaryService, project_diary_food_names
from .system_sensors import CompanionSensorConfig, CompanionSystemSensorService, normalize_game_processes, normalize_health_origin
from .weather import (
    OPEN_METEO_FORECAST_ORIGIN,
    OPEN_METEO_TERMS_REVISION,
    WEATHER_CONDITIONS,
    CompanionWeatherService,
    OpenMeteoWeatherProvider,
    WeatherCache,
    WeatherConfig,
    WeatherObservation,
    build_open_meteo_url,
    classify_weather_failure,
    condition_for_wmo_code,
)
from .media_session import CompanionMediaConfig, CompanionMediaSessionService, MEDIA_PLAYBACK_STATES

__all__ = [
    "CompanionBackupReceipt",
    "CompanionBackupService",
    "CompanionClock",
    "CompanionChatCancelled",
    "CompanionChatError",
    "CompanionChatResult",
    "CompanionChatService",
    "DEFAULT_CHARACTER_PROMPT",
    "DEFAULT_CHARACTER_PROMPT_REVISION",
    "default_character_prompt",
    "CompanionForgetReceipt",
    "CompanionHardForgetError",
    "CompanionHistoryService",
    "CompanionHistoryItem",
    "CompanionHistoryPage",
    "CompanionMemoryBridge",
    "CompanionMemoryBridgeError",
    "CompanionMemoryCandidateResult",
    "CompanionMemoryRecall",
    "CompanionMemoryEvaluationError",
    "EvaluationCorpus",
    "EvaluationDocument",
    "EvaluationMetrics",
    "EvaluationQuery",
    "RetrievalHit",
    "decision",
    "evaluate_fts5_baseline",
    "evaluate_retriever",
    "evaluate_vector_embeddings",
    "hybrid_hits",
    "load_evaluation_corpus",
    "CompanionConflict",
    "FixedCompanionClock",
    "CompanionEvent",
    "CompanionDiaryService",
    "project_diary_food_names",
    "CompanionSensorConfig",
    "CompanionSystemSensorService",
    "CompanionIntegrityError",
    "CompanionInventoryItem",
    "CompanionInteractionEvent",
    "CompanionMasterProfile",
    "CompanionManualService",
    "CompanionMessage",
    "CompanionMessageDependency",
    "CompanionMessagePage",
    "ConversationEpisodeProjection",
    "ConversationRecall",
    "ConversationRecallService",
    "CompanionReminder",
    "CompanionReminderOccurrence",
    "CompanionReminderService",
    "CompanionModelRouteError",
    "CompanionModelRouter",
    "CompanionVisionGrantStore",
    "CompanionVisionService",
    "CompanionVoiceGrantStore",
    "CompanionVoiceTranscriptionService",
    "MAX_VISION_BYTES",
    "MAX_VOICE_AUDIO_BYTES",
    "clean_stale_vision_grants",
    "clean_stale_voice_grants",
    "CompanionNote",
    "CompanionNotesService",
    "CompanionProfileMutation",
    "CompanionProfileService",
    "CompanionPromptBinding",
    "CompanionPromptBindingMutation",
    "CompanionRepository",
    "CompanionRepositoryError",
    "CompanionProviderCancelled",
    "CompanionProviderFailure",
    "CompanionProviderTimeout",
    "CompanionRoutePolicy",
    "CompanionScheduler",
    "CompanionRestoreConflict",
    "CompanionRestorePreflight",
    "CompanionRestoreReceipt",
    "CompanionSchemaStatus",
    "CompanionSchemaTooNew",
    "CompanionSetting",
    "CompanionSession",
    "CompanionStateActionResult",
    "CompanionStateReducer",
    "companion_chat_state_context",
    "CompanionStateSnapshot",
    "CompanionStateProjection",
    "CompanionWalletIntegrity",
    "CompanionWalletEntry",
    "CompanionWalletMutation",
    "CharacterPromptMutation",
    "CHARACTER_PROMPT_ID",
    "COMPANION_ROUTE_KEYS",
    "ComposedPrompt",
    "EventPriority",
    "InMemorySchedulerStore",
    "ManualAuthority",
    "PromptActivationChange",
    "PromptSnapshot",
    "ROUTE_POLICIES",
    "SCHEMA_VERSION",
    "CompanionRoutineService",
    "CompanionRoutineSnapshot",
    "DEFAULT_ROUTINE",
    "ScheduledTrigger",
    "SchedulerMode",
    "validate_profile_input",
    "validate_routine_settings",
    "hourly_key",
    "hourly_text",
    "make_hourly_event",
    "EconomyRules",
    "StateRule",
    "SystemCompanionClock",
    "build_companion_clock",
    "load_economy_rules",
    "CompanionCatalog",
    "CompanionCommerceService",
    "CompanionAppearanceCatalog",
    "CompanionAppearanceService",
    "load_appearance_catalog",
    "CatalogItem",
    "ShopOffer",
    "load_catalog",
    "CompanionFocusService",
    "CompanionAmbientService",
    "FocusSnapshot",
    "normalize_process_name",
    "sample_foreground_process",
    "validate_prompt_content",
    "compose_companion_prompt",
    "require_route_policy",
    "trace_contains_sensitive_body",
    "companion_provider_instruction",
    "parse_companion_chat_envelope",
    "normalize_game_processes",
    "normalize_health_origin",
    "OPEN_METEO_FORECAST_ORIGIN",
    "OPEN_METEO_TERMS_REVISION",
    "WEATHER_CONDITIONS",
    "CompanionWeatherService",
    "OpenMeteoWeatherProvider",
    "WeatherCache",
    "WeatherConfig",
    "WeatherObservation",
    "build_open_meteo_url",
    "classify_weather_failure",
    "condition_for_wmo_code",
    "CompanionMediaConfig",
    "CompanionMediaSessionService",
    "MEDIA_PLAYBACK_STATES",
]
